### ISSUE TITLE
uchiwa rpm seems to be missing items under bower_components folder

### ISSUE THREAD

**Issue by behrendsj** [sensu/uchiwa-build#19]
I update to: uchiwa-0.5.0-1.x86_64.rpm

Uchiwa won't load in the browser, and I'm seeing a bunch of 404's for items under the bower_components folder that don't exist when I check the filesystem.

**Comment by palourde** [comment]
Thanks for reporting this issue @behrendsj. We have a [PR](https://github.com/sensu/uchiwa-build/pull/18) ready, as soon we are done with the tests we will upload the new packages.
