### ISSUE TITLE
Version for latest uchiwa in sensu apt-repos has likely incorrect version number

### ISSUE THREAD

**Issue by petecheslock** [sensu/uchiwa-build#26]
When trying to install the latest version via chef with a version pin, the latest can't be found as it as an extra `1:` in front of the version number.

```
> sudo apt-cache show uchiwa | grep Version
Version: 1:0.14.0-1
Version: 0.13.0-1
Version: 0.12.1-1
Version: 0.12.0-1
Version: 0.11.2-1
```

**Comment by palourde** [comment]
Thank you for reporting this issue. I'll have new packages available as soon as possible!
