### ISSUE TITLE
Build/publish 0.14.3 packages

### ISSUE THREAD

**Issue by jaredledvina** [sensu/uchiwa-build#30]
Hi,

Can we get the debs for 0.14.3 built/published? I checked the download site but looks like they haven't been published. 

Thanks!

**Comment by palourde** [comment]
Hi @jaredledvina,

Sorry for the delay. The 0.14.3 packages should now be on the repositories. For reference, you can also retrieve the packages from https://uchiwa.io/#/download.

Thanks
